name: oblique
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.11
  - mlflow
  - bitstring
  - matplotlib
  - mplhep
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - uproot
  - pytables
  - pip
  - pybind11
  - pip:
      - conifer
      - h5py
      - xgboost
      - ydf
